sudo: false
language: python
cache: pip
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
addons:
  apt:
    packages:
      - libev-dev
install:
  - pip install tox codecov
script:
  - tox
after_success:
  - codecov -e TOXENV